### ISSUE TITLE
Passwording 

### ISSUE THREAD

**Issue by mide2020-16** [Faraticode/Carrot-Events-Real#1]
You can also try to add password to customers account you know for security of privacy

**Comment by Faraticode** [comment]
> You can also try to add password to customers account you know for security of privacy

What do you mean by customers account?

**Comment by mide2020-16** [comment]
What i meant was that in this website every member has is own event or
somethinghe wants to learn so he has to have his personal entry into the
website thathold  his profile just like signing up on ffacebook

**Comment by Faraticode** [comment]
Not all websites 🤨
